name: Automated RC Build

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *" # Every Monday at 02:00 AM UTC (10:00 AM AEST)

env:
  application: Offer Configurator

jobs:

  build-rc-branch:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout Master Branch
        uses: actions/checkout@v3
        with:
          ref: "master"
       
      - name: Set the weekly branch name in Environment
        run: echo "name=rc/$(date +'%Y.%U.%H.%M').0" >> $GITHUB_ENV
        
      - name: Create RC Branch from Master
        run: |
          git config --local user.email "github@faiths.io"
          git config --local user.name "GitHub Actions - RC Automation"
          git checkout -b ${{ env.name }}
          git push --set-upstream origin \
            ${{ env.name }}
    
      - name: Send MS Teams Notification
        uses: simbo/msteams-message-card-action@v1
        with:
          webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
          title: 🛠 Automated RC Branch Created
          message: <table><tr><td><strong>Application:</strong></td><td>${{ env.application }}</td></tr><tr><td><strong>Project:</strong></td><td>${{ github.repository }}</td></tr><tr><td><strong>RC Branch:</strong></td><td>${{ env.name }}</td></tr></table>
          color: 418ff0
          buttons: |
            View Job https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            View Branch https://github.com/${{ github.repository }}/tree/${{ env.name }}
            View Repository https://github.com/${{ github.repository }}
