name: Automated RC Build

on:
  schedule:
    - cron: "* * * * *" # Every Monday at 02:00 AM UTC (10:00 AM AEST)

jobs:
  create-rc-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "master"
      - run: |
          git config --local user.email "github@faiths.io"
          git config --local user.name "GitHub Actions - RC Automation"
      - id: vars
        run: echo "name=$(date +'%Y.%U.%H.%M')" >> $GITHUB_ENV
      - run: |
          git checkout -b rc/${{ env.name }}.0
          git push --set-upstream origin \
            rc/${{ env.name }}.0
