name: Automated RC Build

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *" # Every Monday at 02:00 AM UTC (10:00 AM AEST)

jobs:

  build-rc-branch:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout Master Branch
        uses: actions/checkout@v3
        with:
          ref: "master"
          
      - name: Set the weekly branch name in Environment
        run: echo "name=rc/$(date +'%Y.%U.%H.%M').0" >> $GITHUB_ENV
        
      - name: Create RC Branch from Master
        run: |
          git config --local user.email "github@faiths.io"
          git config --local user.name "GitHub Actions - RC Automation"
          git checkout -b ${{ env.name }}
          git push --set-upstream origin \
            ${{ env.name }}

  notify:
    runs-on: ubuntu-latest
    if: always()
    needs: build-rc-branch
    steps:
    - name: Send a Notification
      id: notify
      uses: thechetantalwar/teams-notify@v2
      with:
        teams_webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
        message: "Github Action Build Number ${{ github.run_number }} Completed for ${{ github.repository }} and the outcome is  ${{ needs.build.result }}."
        
